import os
import json
import requests
from langchain_groq import ChatGroq
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
import sqlite3
load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
JINA_API_KEY = os.getenv("JINA_API_KEY", "")

llm=None

def chat_model():
    global llm
    if not llm:
        llm = ChatGroq(
            model_name="llama-3.3-70b-versatile",
            api_key=GROQ_API_KEY,
            max_tokens=1000,
        )
    return llm

def extract_schema(filename:str)->list[str]:
    conn = sqlite3.connect(filename)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT sql
        FROM sqlite_master
        WHERE type='table' AND name NOT LIKE 'sqlite_%';
    """)
    # Added "if row[0] is not None" to prevent returning None
    table_declarations = [row[0] for row in cursor.fetchall() if row[0] is not None]
    conn.close()
    return table_declarations


def rank_tables(query:str,table_specs:list[str],top_n:int=0)->list[tuple[float,str]]:
    """
    Get sorted pairs of scores and table specifications using the Jina AI API, 
    then return the top N, or all if top_n is 0 or default.
    """
    if not table_specs:
        return []

    if not JINA_API_KEY:
        raise ValueError("JINA_API_KEY is missing from environment variables")

    url = 'https://api.jina.ai/v1/rerank'
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {JINA_API_KEY}'
    }
    data = {
        "model": "jina-reranker-v2-base-multilingual",
        "query": query,
        "documents": table_specs,
        "top_n": top_n if top_n > 0 else len(table_specs)
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        
        result = response.json()
        
        # Jina returns a list of dictionaries in 'results'
        # Example: [{"index": 2, "document": {"text": "..."}, "relevance_score": 0.98}, ...]
        scored_tables = []
        for item in result.get("results", []):
            score = item.get("relevance_score", 0.0)
            
            # The API returns the exact string we sent in 'documents'
            doc_data = item.get("document", "")
            if isinstance(doc_data, dict):
                table_spec = doc_data.get("text", "")
            else:
                table_spec = doc_data
                
            if not table_spec:
                # Fallback if the API only returns the original index
                original_index = item.get("index")
                table_spec = table_specs[original_index]
            
            scored_tables.append((score, table_spec))
            
        return scored_tables

    except requests.exceptions.RequestException as e:
        print(f"Error calling Jina API: {e}")
        # Return unranked tables as a fallback or raise exception
        return [(0.0, spec) for spec in table_specs]
    
def make_sql_prompt(query:str,table_specs:list[tuple[float,str]])->str:
    make_sql_prompt_tmpl_text = (
    """
    Generate a SQL query to answer the following question from the user:
    \"{query_str}\"

    The SQL query should use only tables with the following SQL definitions:

    Table 1:
    {table_1}

    Table 2:
    {table_2}

    Table 3:
    {table_3}

    Make sure you ONLY output an SQL query and no explanation.
    """
    )
    make_sql_prompt_tmpl = PromptTemplate(
        template=make_sql_prompt_tmpl_text,
        input_variables=["query_str", "table_1", "table_2", "table_3"]
    )
    return make_sql_prompt_tmpl.invoke({
        "query_str" : query,
        "table_1" : table_specs[0][1] if len(table_specs) > 0 else "None",
        "table_2" : table_specs[1][1] if len(table_specs) > 1 else "None",
        "table_3" : table_specs[2][1] if len(table_specs) > 2 else "None"
    })

def generate_sql_query(sql_prompt:str)->str:
    llm = chat_model()
    response = llm.invoke(sql_prompt)
    return response.content


def sql_response(sql_query:str, db_path:str):
    sql_query_clean = sql_query.replace("```sql", "").replace("```", "").strip()
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute(sql_query_clean)
    sql_response = cursor.fetchall()
    conn.close()
    return sql_response

def rag_response(query:str, sql_query:str, sql_result:list)->str:
    rag_prompt_tmpl_str = (
    """
Use the information in the JSON table to answer the following user query.
Do not explain anything, just answer concisely. Use natural language in your
answer, not computer formatting.

USER QUERY: {query_str}

JSON table:
{json_table}

This table was generated by the following SQL query:
{sql_query}

Answer ONLY using the information in the table and the SQL query, and if the
table does not provide the information to answer the question, answer
"No Information".
"""
    )
    rag_prompt_tmpl = PromptTemplate(
        template=rag_prompt_tmpl_str,
        input_variables=["query_str", "json_table", "sql_query"]
    )
    rag_prompt = rag_prompt_tmpl.invoke({
        "query_str": query,
        "json_table": json.dumps(sql_result),
        "sql_query": sql_query
    })
    chat_llm = chat_model()
    response = chat_llm.invoke(rag_prompt)
    return response.content